import { useTranslation } from 'react-i18next';
import { ArrowRight, Download } from 'lucide-react';
import SEOHead from '../components/SEOHead';
import { env } from '../config/environment';

/**
 * Free guide — "Dix questions à se poser avant d'automatiser quoi que ce soit".
 *
 * The page exists to give the PDF a stable public URL: it is linked from
 * LinkedIn (post and the profile's Featured section), so /guide must never
 * move. The PDF itself is generated by scripts/guides/dix_questions.py into
 * public/guides/ — edit the script, not the PDF.
 *
 * Copy lives in the `guide` namespace (fr/en/nl); the document is French only,
 * which the EN/NL pages say. Server-side, the route is in KNOWN_ROUTES and
 * SERVICE_NS so crawlers get the ten questions in the raw HTML.
 */
export const GUIDE_PDF = '/guides/dix-questions-avant-d-automatiser.pdf';

type Question = { q: string };

export default function GuidePage() {
  const { t } = useTranslation('guide');
  const questions = (t('list.items', { returnObjects: true }) as Question[]) || [];
  const langNote = t('hero.lang');

  return (
    <>
      <SEOHead title={t('seo.title')} description={t('seo.description')} />

      <section className="bg-canvas text-ink pt-28 lg:pt-32 pb-14 lg:pb-16">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <p className="text-xs font-medium uppercase tracking-[0.2em] text-secondary mb-4">{t('hero.eyebrow')}</p>
            <h1 className="font-display font-bold text-4xl sm:text-5xl leading-[1.08] mb-6">{t('hero.title')}</h1>
            <p className="text-lg text-secondary leading-relaxed max-w-2xl mb-8">{t('hero.intro')}</p>
            <a
              href={GUIDE_PDF}
              download
              className="inline-flex items-center gap-2 rounded-button bg-accent px-7 py-3.5 font-semibold text-white transition-colors hover:bg-accent-dark focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent"
            >
              <Download className="h-5 w-5" strokeWidth={1.5} aria-hidden="true" />
              {t('hero.download')}
            </a>
            <p className="mt-3 text-sm text-secondary">
              {t('hero.note')}
              {langNote ? ` ${langNote}` : ''}
            </p>
          </div>
        </div>
      </section>

      <section className="bg-surface py-14 lg:py-16" aria-labelledby="guide-list">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <h2 id="guide-list" className="font-display font-bold text-3xl sm:text-4xl text-ink leading-[1.1] mb-8">
              {t('list.title')}
            </h2>
            <ol className="space-y-4">
              {questions.map((item, i) => (
                <li key={item.q} className="flex gap-5 rounded-card bg-canvas border border-line p-5">
                  <span className="font-display font-bold text-2xl text-accent/40 tabular-nums leading-none pt-0.5" aria-hidden="true">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <span className="text-ink leading-relaxed">{item.q}</span>
                </li>
              ))}
            </ol>
            <p className="mt-6 text-secondary">{t('list.more')}</p>
          </div>
        </div>
      </section>

      <section className="bg-canvas py-14 lg:py-16" aria-labelledby="guide-call">
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <h2 id="guide-call" className="font-display font-bold text-2xl sm:text-3xl text-ink leading-[1.15] mb-4">
              {t('call.title')}
            </h2>
            <p className="text-secondary leading-relaxed mb-6">{t('call.body')}</p>
            {env.bookingUrl && (
              <a
                href={env.bookingUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 font-medium text-accent-dark hover:gap-3 transition-all"
              >
                {t('call.cta')}
                <ArrowRight className="h-5 w-5" strokeWidth={1.5} aria-hidden="true" />
              </a>
            )}
          </div>
        </div>
      </section>
    </>
  );
}
