/**
 * Réalisations — replayable screenshot capture.
 *
 * The brief (§8.1) asks for a versioned, replayable script rather than
 * hand-taken screenshots: when a site changes, the cover is regenerated by
 * re-running this file, not by someone remembering how they framed it.
 *
 * Playwright is deliberately NOT a dependency of this project. Adding it would
 * put a browser download in the Netlify build path, which is a lot of risk for
 * a script that runs a handful of times a year. Run it on demand instead:
 *
 *     npx playwright install chromium      # once per machine
 *     node scripts/captures/capture.mjs    # all targets
 *     node scripts/captures/capture.mjs enghien rampa   # a subset
 *
 * Output: public/images/realisations/<slug>.jpg
 *
 * ── What must never be captured ────────────────────────────────────────────
 *  - the real supplier workbook: it carries a client's purchase prices and the
 *    names of its suppliers. Use scripts/demo/generate-demo-fournisseurs.py.
 *  - Enghien's footer: it credits the partner by name, and the showcase says
 *    "un cercle d'histoire locale".
 *  - Paperclip's interface: a leadership-meeting tool displays internal
 *    deliberations, including the pricing grid. Excluded below on purpose.
 */

import { mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const outDir = join(root, 'public', 'images', 'realisations');

/** 16:10, matching the card's aspect ratio so nothing is cropped by CSS. */
const VIEWPORT = { width: 1600, height: 1000 };

/**
 * `dismiss` selectors are clicked if present, in order, before the shot:
 * cookie banners and newsletter popups are the two things that ruin a capture.
 * `settle` is an extra wait for pages whose hero animates in.
 */
const targets = [
  {
    slug: 'enghien',
    url: 'https://enghien.srv767464.hstgr.cloud/enghien',
    settle: 2500,
    // The partner is credited in the bar pinned to the bottom of the viewport,
    // and the showcase says "un cercle d'histoire locale". A full-viewport shot
    // publishes the name; 860px stops just above it. Verified on the output —
    // this crop is load-bearing, do not round it back up to 1000.
    clip: { x: 0, y: 0, width: 1600, height: 860 },
  },
  {
    slug: 'rampa',
    url: 'https://rampa.srv767464.hstgr.cloud/',
    settle: 2500,
  },
  {
    slug: 'dreamoracle',
    url: 'https://dreamoracle.eu',
    settle: 3000,
    dismiss: ['button:has-text("Accepter")', 'button:has-text("Accept")'],
  },
  {
    slug: 'audityo',
    url: 'https://audityo.eu',
    settle: 3000,
    dismiss: ['button:has-text("Accepter")', 'button:has-text("Accept")'],
  },
  {
    slug: 'artpero',
    url: 'https://lartpero.ainspiration.eu',
    settle: 3000,
    dismiss: ['button:has-text("Accepter")'],
  },
  {
    slug: 'tl-services',
    url: 'https://tlservices.distr-action.com',
    settle: 2500,
    dismiss: ['button:has-text("Accepter")'],
  },
  {
    slug: 'labo-nostalgie',
    url: 'https://laurent7850.github.io/playlist-generator/',
    settle: 2500,
  },
  {
    slug: 'playlist-spotify',
    url: 'https://distraction-spotify-playlist.netlify.app/',
    settle: 2000,
  },
  {
    slug: 'chat-ia-site',
    // The live chat on our own site. Local by default so the capture can be
    // regenerated without waiting for a deploy; override with CAPTURE_BASE.
    url: `${process.env.CAPTURE_BASE ?? 'http://localhost:5173'}/`,
    settle: 3000,
    dismiss: [
      'button:has-text("Cookies essentiels uniquement")',
      'button:has-text("Non merci")',
    ],
  },
];

const wanted = process.argv.slice(2);
const selected = wanted.length
  ? targets.filter((t) => wanted.includes(t.slug))
  : targets;

if (!selected.length) {
  console.error(`No target matched. Known slugs: ${targets.map((t) => t.slug).join(', ')}`);
  process.exit(1);
}

const { chromium } = await import('playwright');

await mkdir(outDir, { recursive: true });

const browser = await chromium.launch();
const results = [];

for (const target of selected) {
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: 1,
    locale: 'fr-BE',
    // Motion is decoration here; a half-played entrance animation makes a
    // capture look broken.
    reducedMotion: 'reduce',
  });
  const page = await context.newPage();

  try {
    await page.goto(target.url, { waitUntil: 'networkidle', timeout: 45_000 });

    for (const selector of target.dismiss ?? []) {
      const button = page.locator(selector).first();
      if (await button.count().catch(() => 0)) {
        await button.click({ timeout: 3000 }).catch(() => {});
      }
    }

    await page.waitForTimeout(target.settle ?? 1500);

    const file = join(outDir, `${target.slug}.jpg`);
    await page.screenshot({
      path: file,
      type: 'jpeg',
      quality: 82,
      clip: target.clip,
    });
    results.push({ slug: target.slug, status: 'ok', file });
    console.log(`  ok   ${target.slug}`);
  } catch (error) {
    // A failed target must not abort the run: one unreachable site should not
    // cost the other nine captures.
    results.push({ slug: target.slug, status: 'failed', reason: error.message });
    console.log(`  FAIL ${target.slug} — ${error.message.split('\n')[0]}`);
  } finally {
    await context.close();
  }
}

await browser.close();

const failed = results.filter((r) => r.status === 'failed');
console.log(`\n${results.length - failed.length}/${results.length} captures written to public/images/realisations/`);
if (failed.length) {
  console.log('Failed:', failed.map((f) => f.slug).join(', '));
  process.exit(1);
}
